#!/usr/bin/env python
"""
Launch the pipumpking application
"""
import sys
import os
sys.path.append(os.path.abspath("."))
from pipumpkin.pumpkin import PiPumpkin

pumpkin = PiPumpkin()
pumpkin.main()
