#!/usr/bin/env python
### BEGIN INIT INFO
# Provides:          pipupmkin
# Required-Start:    $remote_fs $syslog $networking
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script which will start / stop a program a boot / shutdown.
### END INIT INFO

"""
This is a daemon-style wrapper around PiPumpkin.main()
"""
import argparse
import daemon
import os
import signal
import sys

sys.path.append(os.path.abspath("."))
from pipumpkin.pumpkin import PiPumpkin

PIDFILE = "/var/run/pipumpkin.pid"

def main():
    """Use a PID lock file
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("action")
    args = parser.parse_args()
    if args.action == "start":
        start()
    elif args.action == "stop":
        stop()
    
def start():
    """
    """
    if os.path.exists(PIDFILE):
        print "%s is already started! Remove %s" % (sys.argv[0], PIDFILE)
        return

    with open(PIDFILE, "w") as f:
        f.write(str(os.getpid()))

    with daemon.DaemonContext():
        pipumpkin = PiPumpkin()
        pipumpkin.main()

    os.remove(PIDFILE)

def stop():
    """
    """
    if not os.path.exists(PIDFILE):
        print "Could not find {0}! Has the daemon been started?".format(PIDFILE)
    with open(PIDFILE, "r") as file:
        pid = int(file.read())
    try:    
        os.kill(pid, signal.SIGKILL)
        print "Killed {0}".format(pid)
    except OSError:
        print "Could not find PID {0}. Removing {1}".format(pid, PIDFILE)
    os.remove(PIDFILE)

if __name__ == "__main__":
    main()
    
