#!/usr/bin/env python
"""
This is a daemon-style wrapper around PiPumpkin.main()
"""
import argparse
import daemon
import os
import sys

sys.path.append(os.path.abspath("."))
from pipumpkin.pumpkin import PiPumpkin

PIDFILE = "/var/log/pipumpkin.pid"

def main():
    """Use a PID lock file
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("action")
    args = parser.parse_args()
    if args.action == "start":
        start()
    
def start():
    """
    """
    if os.path.exists(PIDFILE):
        print "%s is already started! Remove %s" % (sys.argv[0], PIDFILE)
        return

    with open(PIDFILE, "w") as f:
        f.write(str(os.getpid()))

    with daemon.DaemonContext():
        pipumpkin = PiPumpkin()
        pipumpkin.main()

    os.remove(PIDFILE)

if __name__ == "__main__":
    main()
    
